version: '3'
services:
  backend:
    build:
      dockerfile: Dockerfile
      context: .
    entrypoint: ./target/release/ohmybook_rust
    ports:
      - "8001"
    volumes:
      - ./:/code
  
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    ports:
      - "4000:4000"
    deploy:
      resources:
        limits:
          memory: 30M
          cpus: '2'
